services:
  professor:
    build: .
    container_name: node_professor
    environment:
      - NODE_ID=PROFESSOR-1
      - NODE_ROLE=PROFESSOR
      - PORT=8080
    ports:
      - "5001:8080"
    networks:
      - blockchain-network
    restart: unless-stopped

  aluno:
    build: .
    container_name: node_aluno
    environment:
      - NODE_ID=ALUNO-1
      - NODE_ROLE=ALUNO
      - PORT=8080
    ports:
      - "5002:8080"
    networks:
      - blockchain-network
    restart: unless-stopped

  dae:
    build: .
    container_name: node_dae
    environment:
      - NODE_ID=DAE-1
      - NODE_ROLE=DAE
      - PORT=8080
    ports:
      - "5003:8080"
    networks:
      - blockchain-network
    restart: unless-stopped

networks:
  blockchain-network:
    driver: bridge
